template_repository_url=https://github.com/CleanroomMC/ForgeDevEnv.git
template_repository_ref=master
root_package=com.mahghuuuls
mod_authors=Mahghuuuls
minecraft_username=Mahghuuuls
use_modern_java_syntax=false
license=MIT